# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170712_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='credit_multiplier',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
