# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170712_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorMicrovoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microvocs', to='core.Language')),
                ('microvoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microvoc', to='core.MicroVocabulary')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microvocs', to='core.TranslatorProfile')),
            ],
        ),
    ]
