# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_translatormicrovoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='microvocabulary',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
