# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_microvocabulary_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive_translator', models.BooleanField(default=True)),
                ('from_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='froms', to='core.Language')),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toes', to='core.Language')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='core.TranslatorProfile')),
            ],
        ),
    ]
