# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20170718_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='language',
        ),
        migrations.AddField(
            model_name='appointmentclosure',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='language_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certified_from', to='core.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='language_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certified_to', to='core.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificationissuer',
            name='city',
            field=models.CharField(default='Padova', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificationissuer',
            name='country',
            field=models.CharField(default='Italy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(default='Via Polese 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(default='Padova', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(default='Italy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='fax',
            field=models.CharField(default='123456789', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='mail',
            field=models.CharField(default='mail@mail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tel',
            field=models.CharField(default='123456789', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='vat_number',
            field=models.CharField(default='1234568769', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='website',
            field=models.URLField(default='http://www.google.com'),
            preserve_default=False,
        ),
    ]
