# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170725_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatorlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='translatormicrovoc',
            name='language',
        ),
        migrations.AddField(
            model_name='translatorlanguage',
            name='language_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translate_to', to='core.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatorlanguage',
            name='language_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translate_from', to='core.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatormicrovoc',
            name='language_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='microvoc_to', to='core.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatormicrovoc',
            name='language_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='microvoc_from', to='core.Language'),
            preserve_default=False,
        ),
    ]
