# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170725_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.URLField()),
                ('date', models.DateField()),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.TranslatorProfile')),
            ],
        ),
    ]
