# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_translatorinvoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='microvocs',
            field=models.ManyToManyField(to='core.MicroVocabulary'),
        ),
    ]
