# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_appointment_microvocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
