# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_certificationlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CertificationLevel'),
        ),
    ]
