# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170727_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='it', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatormicrovoc',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microvoc', to='core.TranslatorLanguage'),
        ),
        migrations.AddField(
            model_name='translatormode',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode', to='core.TranslatorLanguage'),
        ),
    ]
