# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20171106_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Cable Internet',
            },
        ),
        migrations.CreateModel(
            name='CableInternetProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Cable Internet Provider',
            },
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Computer Model',
            },
        ),
        migrations.CreateModel(
            name='MobileInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Mobile Internet',
            },
        ),
        migrations.CreateModel(
            name='MobileInternetProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Mobile Internet Provider',
            },
        ),
        migrations.CreateModel(
            name='TabletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Tablet Model',
            },
        ),
        migrations.CreateModel(
            name='TelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AA Telephone Model',
            },
        ),
    ]
