"""
Django settings for tradulive_back project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os


dbs = {
    "psql":"",
    "mysql":"",
    "oracle":"",
    "sqlite":"django.db.backends.sqlite3",
    
    "postgis":"",
    "spatialite":"",
    
    "psql_multitenant":"tenant_schemas.postgresql_backend",
}

def db_from_env(default_conf):
    
    ret = default_conf
    
    DB_ENGINE = os.getenv("DB_ENGINE")
    DB_ENGINE = dbs.get(DB_ENGINE, "")
    DB_NAME   = os.getenv("DB_NAME")
    DB_PASS   = os.getenv("DB_PASS")
    DB_USER   = os.getenv("DB_USER")
    DB_HOST   = os.getenv("DB_HOST")
    DB_PORT   = os.getenv("DB_PORT")
    DB_EXTRAS = os.getenv("DB_EXTRAS")

    print(DB_ENGINE, DB_NAME, DB_USER, DB_PASS, DB_HOST, DB_PORT)

    if DB_ENGINE != "":
        ret = {
            "ENGINE":DB_ENGINE
        }
    if DB_NAME:
        ret["NAME"] = DB_NAME
    if DB_USER:
        ret["USER"] = DB_USER
    if DB_PASS:
        ret["PASSWORD"] = DB_PASS
    if DB_HOST:
        ret["HOST"] = DB_HOST
    if DB_PORT:
        ret["PORT"] = DB_PORT
        
    return ret

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '64xd5$svse50d^^f%uum_os1dzupn&gh+hhv5fk%6b$z*-p1mt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "app.tradulive.eu", "app.staging.tradulive.eu"]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'timezone_field',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tradulive_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tradulive_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': db_from_env({
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    })
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

CORS_ORIGIN_ALLOW_ALL = True